python train_cnn3D.py \
--data_hdf5="/mnt/data/LungNodules/features_rotatable.hdf5" \
--metadata_json="/mnt/data/LungNodules/features_rotatable_metadata.json" \
--tag="nodulesCNN3D_extra-features_azim-rotations" \
--max_epochs=100 \
--n_trainings=5 \
--training_batch_size=16 \
--validation_batch_size=16 \
--max_batch_size=64 \
--increase_batch \
--random_seed=0 \
--train_frac=0.7 \
--loss_function="weighted_crossentropy" \
--extra_features center_of_mass_norm nodule_volume_norm \
--do_rotations
