python train_unet.py \
--data_hdf5="/xilinx/scratch/covid_ct_data/14Jul2020_z_score_downsample256/features.hdf5" \
--metadata_json="/xilinx/scratch/covid_ct_data/14Jul2020_z_score_downsample256/features.json" \
--n_extra_slices=1 \
--extra_slice_step=1 \
--tag="2p5_0extra" \
--max_epochs=1 \
--n_trainings=1 \
--training_batch_size=16 \
--validation_batch_size=16 \
--max_batch_size=64 \
--random_seed=0 \
--train_frac=0.7 >& 2p5_1extra_test_logs.txt
