# The UNIVERSE defines an execution environment. You will almost always use VANILLA.
Universe = vanilla

# These are good base requirements for your jobs on OSG.
Requirements = HAS_SINGULARITY == True
request_cpus = 1
request_gpus = 1
request_memory = 1 GB
#request_disk = 1 GB

# Define project
+ProjectName = "COVID19_UCSD_Hsiao"

# Require stashcache
+WantsStashCache = true
requirements = OSGVO_OS_STRING == "RHEL 7" && Arch == "X86_64" && HAS_MODULES == True

# Singularity image to use
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/sjmay/zephyr:latest"

# EXECUTABLE is the program your job will run It's often useful
# to create a shell script to "wrap" your actual work.
Executable = executable.sh
Arguments = 

# inputs/outputs
transfer_input_files = package.tar.gz
transfer_output_files = 

# ERROR and OUTPUT are the error and output channels from your job
# that HTCondor returns from the remote host.
Error = outputs/$(Cluster).$(Process).error
Output = outputs/$(Cluster).$(Process).output

# The LOG file is where HTCondor places information about your
# job's status, success, and resource consumption.
Log = outputs/$(Cluster).$(Process).log

# Send the job to Held state on failure. 
#on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 1 hour, up to a maximum of 5 retries.
#periodic_release =  (NumJobStarts < 5) && ((CurrentTime - EnteredCurrentStatus) > 60*60)

# QUEUE is the "start button" - it launches any jobs that have been
# specified thus far.
queue 1

